# Generated by Django 4.1.7 on 2023-05-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='tipo',
        ),
    ]
