# Generated by Django 4.1.7 on 2023-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_espacio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='image1',
            field=models.ImageField(default=0, upload_to='base/Images/EspaciosImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacio',
            name='image2',
            field=models.ImageField(default=1, upload_to='base/Images/EspaciosImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacio',
            name='image3',
            field=models.ImageField(default='none', upload_to='base/Images/EspaciosImages'),
            preserve_default=False,
        ),
    ]
