# Generated by Django 4.1.7 on 2023-05-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_espacio_image1_espacio_image2_espacio_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='baño',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacio',
            name='baño_ducha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacio',
            name='espejos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacio',
            name='estacionamiento',
            field=models.BooleanField(default=False),
        ),
    ]
