# Generated by Django 4.1.7 on 2023-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_espacio_baño_espacio_baño_ducha_espacio_espejos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='baño',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='baño_ducha',
            field=models.BooleanField(default=True),
        ),
    ]
