# Generated by Django 4.1.7 on 2023-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_espacio_baño_alter_espacio_baño_ducha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='baño',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='baño_ducha',
            field=models.BooleanField(default=False),
        ),
    ]
