# Generated by Django 4.1.7 on 2023-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_espacio_baño_alter_espacio_baño_ducha'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='direccion',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
