# Generated by Django 4.1.7 on 2023-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_baño_ducha_espacio_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='superficie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
