# Generated by Django 4.1.7 on 2023-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_espacio_superficie'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='tipoEspacio',
            field=models.CharField(choices=[('Gimnasio', 'Gimnasio'), ('Arte', 'Arte'), ('ArtMarcial', 'ArtMarcial'), ('Cocina', 'Cocina'), ('Danza', 'Danza'), ('Musica', 'Musica'), ('Gimnasio', 'Gimnasio'), ('Fotografia', 'Fotografia'), ('Showroom', 'Showroom'), ('Otros', 'Otros')], default='none', max_length=15),
            preserve_default=False,
        ),
    ]
