# Generated by Django 4.1.7 on 2023-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_espacio_tipoespacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('fotoPerfil', models.ImageField(upload_to='base/Images/EspaciosImages')),
                ('tipoEspacio', models.CharField(choices=[('Femenino', 'Feminino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=20)),
            ],
        ),
    ]
