# Generated by Django 4.1.7 on 2023-06-09 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='user',
        ),
        migrations.AddField(
            model_name='espacio',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
