# Generated by Django 4.1.7 on 2023-06-13 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_espacio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='apellido',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='dni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
