# Generated by Django 4.1.7 on 2023-06-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_reserva_apellido_reserva_dni_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipoPago',
            field=models.CharField(choices=[('Efectivo en el Lugar', 'Efectivo en el Lugar'), ('Transferencia', 'Transferencia')], default='none', max_length=30),
            preserve_default=False,
        ),
    ]
