# Generated by Django 4.1.7 on 2023-06-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_reserva_tipopago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
