# Generated by Django 4.1.7 on 2023-06-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='post',
        ),
    ]
