# Generated by Django 4.1.7 on 2023-06-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_reserva_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.espacio'),
            preserve_default=False,
        ),
    ]
