# Generated by Django 4.1.7 on 2023-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_reserva_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nroCelular',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
