# Generated by Django 4.1.7 on 2023-07-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_reseñareserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
