# Generated by Django 4.1.7 on 2023-07-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='estado',
            field=models.CharField(choices=[('espera_aprobacion', 'Espera de Aprobación'), ('publicado', 'Publicado')], default='espera_aprobacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('espera_aprobacion', 'Espera de Aprobación'), ('aprobada', 'Aprobada'), ('cancelada', 'Cancelada'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('pagada', 'Pagada')], default='espera_aprobacion', max_length=20),
        ),
    ]
