# Generated by Django 4.1.7 on 2023-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_espacio_estado_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='estado',
            field=models.CharField(choices=[('EnEsperaAprobacion', 'EnEsperaAprobacion'), ('Publicado', 'Publicado'), ('Rechazado', 'Rechazado')], default='EnEsperaAprobacion', max_length=20),
        ),
    ]
