# Generated by Django 4.1.7 on 2023-08-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='espacio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.espacio'),
            preserve_default=False,
        ),
    ]
